// 处理游戏账号数据,提取游戏名称和账号的映射关系
const gameAccountsData = {
  "刺客信条： 英灵殿": "ceshiyuan10",
  "狂野飙车：传奇集结": "ceshiyuan3\nsanmu1596",
  "渡神纪 芬尼斯崛起\n（lmmortals Fenyx Rising）": "ceshiyuan41",
  "幻兽帕鲁\nPalworld": "ceshiyuan6",
  "博德之门 3\n（Baldur's Gate 3 ）": "ceshiyuan7",
  "ARMORED CORE VI FIRES OF RUBICON\n机战佣兵VI 境界天火": "ceshiyuan41",
  "古墓丽影：暗影\n（Shadow of the Tomb Raider）": "ceshiyuan8\nceshiyuan33",
  "Maneater\n食人鲨": "Joesyang1596",
  "Path of Exile\n流放之路": "wegame平台免费游戏",
  "霍格沃茨之遗\n（Hogwarts Legacy）": "ceshiyuan8",
  "创世战车": "wegame平台免费游戏",
  "Zombie Army 4: Dead War\n僵尸部队4": "tenevr",
  "Kena: Bridge of Spirits\nKena：精神之桥": "ceshiyuan41",
  "Chained Together": "ceshiyuan66",
  "ELDEN RING 艾尔登法环": "ceshiyuan21",
  "最后纪元\n（Last Epoch）": "ceshiyuan33",
  "黑神话：悟空": "steam（ceshiyuan33）\n/wegame",
  "Marvel's Spider-Man: Miles Morales\n漫威蜘蛛侠": "ceshiyuan8",
  "暗黑破坏神4": "sanmu1596",
  "激战2": "wegame平台免费游戏",
  "Middle-earth: Shadow of War\n中土世界：战争之影": "ceshiyuan7",
  "High On Life": "ceshiyuan6",
  "消逝的光芒2\nDying Light 2 Stay Human": "sanmu1596",
  "逆战": "wegame平台免费游戏",
  "小小梦魇2": "tenevr",
  "剑灵（正式服）": "wegame平台免费游戏",
  "巫师3：狂猎": "ceshiyuan41",
  "Need for Speed: Rivals": "ceshiyuan6",
  "皇牌空战7：未知空域\n（ACE COMBAT™ 7: SKIES UNKNOWN）": "ceshiyuan33",
  "永劫无间（Naraka: Bladepoint）": "steam免费游戏",
  "无畏契约": "wegame免费游戏",
  "真.三国无双8": "ceshiyuan33",
  "MONSTER HUNTER RISE\n怪物猎人：崛起": "Joesyang1596",
  "死亡搁浅（Death Stranding）": "sanmu1596",
  "深海迷航": "tenevr",
  "暗区突围": "wegame免费游戏",
  "三位一体5": "ceshiyuan33",
  "暗喻幻想：ReFantazio": "tenevr",
  "碧波之下": "ceshiyuan8",
  "原子之心": "ceshiyuan33",
  "上古卷轴5:天际\n（The Elder Scrolls V: Skyrim Special Edition）": "sanmu1596",
  "铁甲雄兵": "wegame平台免费游戏",
  "Fallout 4\n辐射4": "ceshiyuan41",
  "Fallout 76": "ceshiyuan66",
  "奇异小队\n（Strange Brigade）": "ceshiyuan6",
  "茧中蚕\n（Hollow Cocoon）": "sanmu1596",
  "魔兽世界": "战网平台免费游戏",
  "Lies of P [3D Ultra] 匹诺曹的谎言": "ceshiyuan7",
  "Starfield\n星空": "ceshiyuan7",
  "Sons Of The Forest\n森林之子": "tenevr",
  "PayDay3": "ceshiyuan21",
  "UNCHARTED™: 盗贼传奇合辑": "ceshiyuan41",
  "NBA2KOL2": "wegame平台免费游戏",
  "Returnal\n死亡回归": "ceshiyuan41",
  "流放之路2": "ceshiyuan6@gmail.com",
  "狙击精英4": "ceshiyuan41",
  "Mirror's Edge Catalyst\n镜之边缘：Catalyst": "ceshiyuan7",
  "INJUSTICE2\n不义联盟2": "ceshiyuan7",
  "只狼\n(Sekiro™ Shadows Die Twice)": "ceshiyuan7",
  "刺客信条： 奥德赛": "ceshiyuan6",
  "仙剑奇侠传七": "ceshiyuan10",
  "英雄联盟lol": "wegame平台免费游戏",
  "碧蓝幻想\n（Granblue Fantasy: Relink）": "ceshiyuan8",
  "无主之地3": "ceshiyuan7",
  "The Last of Us\n最后生还者": "ceshiyuan8",
  "Dead Space\n死亡空间": "steam账号：wezgame",
  "冲就完事模拟器": "ceshiyuan10",
  "极限竞速：地平线 5\nForza Horizon 5": "ceshiyuan33",
  "女神异闻录5 战略版": "ceshiyuan33",
  "战神4 / (战神God of War系列)": "ceshiyuan33",
  "GRID（2019）": "ceshiyuan41",
  "LEGO® Star Wars™: The Skywalker Saga\n乐高星球大战 天行者传奇": "ceshiyuan41",
  "底特律：化身为人": "ceshiyuan6",
  "HELLDIVERS™ 2": "ceshiyuan66",
  "龙之信条2": "ceshiyuan7",
  "模拟飞行\n（Microsoft Flight Simulator）": "ceshiyuan7",
  "Monster Hunter: World\n怪物猎人：世界": "ceshiyuan8",
  "遗迹：灰烬重生\nRemnant: From the Ashes": "ceshiyuan8",
  "猛兽派对": "ceshiyuan8",
  "HIFI RUSH": "Joesyang1596",
  "生化危机4\n（Resident Evil 4）": "sanmu1596",
  "星球大战 绝地：陨落的骑士团\nStar Wars Jedi: Fallen Order": "sanmu1596",
  "DCS\n（DCS World Steam Edition）": "steam免费游戏",
  "七日世界": "steam免费游戏",
  "鬼泣5\n（Devil May Cry 5）": "tenevr",
  "三角洲行动": "wegame免费游戏",
  "全境封锁2": "wegame平台免费游戏",
  "命运方舟": "wegame平台免费游戏",
  "卡拉彼丘": "wegame平台免费游戏",
  "天涯明月刀\nMoonlight Blade dx12": "wegame平台免费游戏",
  "QQ飞车-端游\nQQ Speed (GameApp)": "wegame平台免费游戏",
  "NieR:Automata™": "ceshiyuan21",
  "嗜血印\n（ BloodySpell）": "ceshiyuan21",
  "反恐精英2\n（Counter-Strike 2）": "steam免费游戏",
  "NBA 2K23": "ceshiyuan21",
  "Ratchet & Clank:Rift Apart\n瑞奇与叮当：时空跳转": "ceshiyuan21",
  "赛博朋克：2077": "ceshiyuan41",
  "泰坦陨落2\n（Titanfall 2）": "ceshiyuan33",
  "装甲战争": "wegame平台免费游戏",
  "DARK SOULS™ III\n黑暗之魂 3": "ceshiyuan7",
  "Ghost of Tsushima\n对马岛之魂": "ceshiyuan10",
  "无人深空": "ceshiyuan10",
  "荒野大镖客2\n（Red Dead Redemption 2）": "ceshiyuan21",
  "流放之路：降临": "wegame"
};

// 兼容浏览器和Node.js环境
if (typeof module !== 'undefined' && module.exports) {
  module.exports = gameAccountsData;
}
