#!/usr/bin/env node
// 游戏引擎数据恢复脚本 - 在服务器上运行
const sqlite3 = require("sqlite3").verbose();
const path = require("path");
const db = new sqlite3.Database(path.join(__dirname, "database.sqlite"));

db.serialize(() => {
  // 添加列（如已存在会报错，忽略即可）
  db.run("ALTER TABLE games ADD COLUMN game_engine TEXT", () => {});

  // 更新数据
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 1);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "AnvilNext 2.0", 2);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "AnvilNext 2.0", 3);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Divinity 4.0", 4);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Decima", 5);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Blizzard Engine", 6);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "C-Engine", 7);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "KOEI Warrior Engine", 8);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 9);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 10);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "AnvilNext 2.0", 11);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 12);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 5", 13);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "FromSoftware Engine", 14);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Foundation Engine", 15);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Creation Engine", 16);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Asura Engine", 17);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 18);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "REDengine 3", 19);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 20);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 5", 21);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 5", 22);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 23);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Asura Engine", 24);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 25);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 26);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Creation Engine", 27);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Frostbite", 28);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Insomniac Engine", 29);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Creation Engine 2", 30);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 31);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "FromSoftware Engine", 32);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 33);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Naughty Dog Engine", 34);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Frostbite", 35);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "LithTech", 36);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 3", 37);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 38);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Asura Engine", 39);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RE Engine", 40);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 41);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 42);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Creation Engine", 43);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 44);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 45);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 46);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 47);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (Frozenbyte)", 48);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "FromSoftware Engine", 49);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 50);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 51);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom", 52);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom", 53);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 3", 54);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 3", 55);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 56);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 57);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 58);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 59);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Evolution Engine", 60);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Dagor Engine", 61);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (2K)", 62);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (ArenaNet)", 63);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (Blizzard)", 64);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom", 65);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "CryEngine", 66);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 67);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 68);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 69);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Source 2", 70);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "REDengine 4", 71);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "FromSoftware Engine", 72);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (Eagle Dynamics)", 73);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Frostbite", 74);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 5", 75);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 5", 76);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Decima", 77);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RE Engine", 78);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RE Engine", 79);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "ForzaTech", 80);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Sucker Punch Engine", 81);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Santa Monica Engine", 82);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Cygames Engine", 83);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "EGO Engine", 84);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Decima", 85);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RE Engine", 86);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (Riot)", 87);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "NTT Engine", 88);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 3", 89);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Frostbite", 90);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "MT Framework", 91);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "QuickSilver", 92);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (2K)", 93);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Platinum Engine", 94);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom (Hello Games)", 95);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 96);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unity", 97);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 98);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 99);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "PhysX Engine", 100);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Insomniac Engine", 101);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RAGE", 102);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 103);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "RE Engine", 104);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Unreal Engine 4", 105);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Naughty Dog Engine", 106);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Snowdrop", 107);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Source", 108);
  db.run("UPDATE games SET game_engine = ? WHERE id = ?", "Custom", 109);

  // 验证
  db.get("SELECT COUNT(*) as total FROM games", (e, r) => {
    console.log("总游戏数:", r.total);
    db.get("SELECT COUNT(*) as c FROM games WHERE game_engine IS NOT NULL AND game_engine != \"\"", (e2, r2) => {
      console.log("已填引擎数:", r2.c);
      db.close();
    });
  });
});
