-- 游戏引擎数据恢复脚本
-- 执行: sqlite3 database.sqlite < update_game_engine.sql

ALTER TABLE games ADD COLUMN game_engine TEXT;

UPDATE games SET game_engine="Unreal Engine 4" WHERE id=1;
UPDATE games SET game_engine="AnvilNext 2.0" WHERE id=2;
UPDATE games SET game_engine="AnvilNext 2.0" WHERE id=3;
UPDATE games SET game_engine="Divinity 4.0" WHERE id=4;
UPDATE games SET game_engine="Decima" WHERE id=5;
UPDATE games SET game_engine="Blizzard Engine" WHERE id=6;
UPDATE games SET game_engine="C-Engine" WHERE id=7;
UPDATE games SET game_engine="KOEI Warrior Engine" WHERE id=8;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=9;
UPDATE games SET game_engine="Unity" WHERE id=10;
UPDATE games SET game_engine="AnvilNext 2.0" WHERE id=11;
UPDATE games SET game_engine="Unity" WHERE id=12;
UPDATE games SET game_engine="Unreal Engine 5" WHERE id=13;
UPDATE games SET game_engine="FromSoftware Engine" WHERE id=14;
UPDATE games SET game_engine="Foundation Engine" WHERE id=15;
UPDATE games SET game_engine="Creation Engine" WHERE id=16;
UPDATE games SET game_engine="Asura Engine" WHERE id=17;
UPDATE games SET game_engine="Unity" WHERE id=18;
UPDATE games SET game_engine="REDengine 3" WHERE id=19;
UPDATE games SET game_engine="Unity" WHERE id=20;
UPDATE games SET game_engine="Unreal Engine 5" WHERE id=21;
UPDATE games SET game_engine="Unreal Engine 5" WHERE id=22;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=23;
UPDATE games SET game_engine="Asura Engine" WHERE id=24;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=25;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=26;
UPDATE games SET game_engine="Creation Engine" WHERE id=27;
UPDATE games SET game_engine="Frostbite" WHERE id=28;
UPDATE games SET game_engine="Insomniac Engine" WHERE id=29;
UPDATE games SET game_engine="Creation Engine 2" WHERE id=30;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=31;
UPDATE games SET game_engine="FromSoftware Engine" WHERE id=32;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=33;
UPDATE games SET game_engine="Naughty Dog Engine" WHERE id=34;
UPDATE games SET game_engine="Frostbite" WHERE id=35;
UPDATE games SET game_engine="LithTech" WHERE id=36;
UPDATE games SET game_engine="Unreal Engine 3" WHERE id=37;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=38;
UPDATE games SET game_engine="Asura Engine" WHERE id=39;
UPDATE games SET game_engine="RE Engine" WHERE id=40;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=41;
UPDATE games SET game_engine="Unity" WHERE id=42;
UPDATE games SET game_engine="Creation Engine" WHERE id=43;
UPDATE games SET game_engine="Unity" WHERE id=44;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=45;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=46;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=47;
UPDATE games SET game_engine="Custom (Frozenbyte)" WHERE id=48;
UPDATE games SET game_engine="FromSoftware Engine" WHERE id=49;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=50;
UPDATE games SET game_engine="Unity" WHERE id=51;
UPDATE games SET game_engine="Custom" WHERE id=52;
UPDATE games SET game_engine="Custom" WHERE id=53;
UPDATE games SET game_engine="Unreal Engine 3" WHERE id=54;
UPDATE games SET game_engine="Unreal Engine 3" WHERE id=55;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=56;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=57;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=58;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=59;
UPDATE games SET game_engine="Evolution Engine" WHERE id=60;
UPDATE games SET game_engine="Dagor Engine" WHERE id=61;
UPDATE games SET game_engine="Custom (2K)" WHERE id=62;
UPDATE games SET game_engine="Custom (ArenaNet)" WHERE id=63;
UPDATE games SET game_engine="Custom (Blizzard)" WHERE id=64;
UPDATE games SET game_engine="Custom" WHERE id=65;
UPDATE games SET game_engine="CryEngine" WHERE id=66;
UPDATE games SET game_engine="Unity" WHERE id=67;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=68;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=69;
UPDATE games SET game_engine="Source 2" WHERE id=70;
UPDATE games SET game_engine="REDengine 4" WHERE id=71;
UPDATE games SET game_engine="FromSoftware Engine" WHERE id=72;
UPDATE games SET game_engine="Custom (Eagle Dynamics)" WHERE id=73;
UPDATE games SET game_engine="Frostbite" WHERE id=74;
UPDATE games SET game_engine="Unreal Engine 5" WHERE id=75;
UPDATE games SET game_engine="Unreal Engine 5" WHERE id=76;
UPDATE games SET game_engine="Decima" WHERE id=77;
UPDATE games SET game_engine="RE Engine" WHERE id=78;
UPDATE games SET game_engine="RE Engine" WHERE id=79;
UPDATE games SET game_engine="ForzaTech" WHERE id=80;
UPDATE games SET game_engine="Sucker Punch Engine" WHERE id=81;
UPDATE games SET game_engine="Santa Monica Engine" WHERE id=82;
UPDATE games SET game_engine="Cygames Engine" WHERE id=83;
UPDATE games SET game_engine="EGO Engine" WHERE id=84;
UPDATE games SET game_engine="Decima" WHERE id=85;
UPDATE games SET game_engine="RE Engine" WHERE id=86;
UPDATE games SET game_engine="Custom (Riot)" WHERE id=87;
UPDATE games SET game_engine="NTT Engine" WHERE id=88;
UPDATE games SET game_engine="Unreal Engine 3" WHERE id=89;
UPDATE games SET game_engine="Frostbite" WHERE id=90;
UPDATE games SET game_engine="MT Framework" WHERE id=91;
UPDATE games SET game_engine="QuickSilver" WHERE id=92;
UPDATE games SET game_engine="Custom (2K)" WHERE id=93;
UPDATE games SET game_engine="Platinum Engine" WHERE id=94;
UPDATE games SET game_engine="Custom (Hello Games)" WHERE id=95;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=96;
UPDATE games SET game_engine="Unity" WHERE id=97;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=98;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=99;
UPDATE games SET game_engine="PhysX Engine" WHERE id=100;
UPDATE games SET game_engine="Insomniac Engine" WHERE id=101;
UPDATE games SET game_engine="RAGE" WHERE id=102;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=103;
UPDATE games SET game_engine="RE Engine" WHERE id=104;
UPDATE games SET game_engine="Unreal Engine 4" WHERE id=105;
UPDATE games SET game_engine="Naughty Dog Engine" WHERE id=106;
UPDATE games SET game_engine="Snowdrop" WHERE id=107;
UPDATE games SET game_engine="Source" WHERE id=108;
UPDATE games SET game_engine="Custom" WHERE id=109;
